DROP DATABASE IF EXISTS `crud-demo`;
CREATE DATABASE `crud-demo`;
USE `crud-demo`;
DROP TABLE IF EXISTS `crud-demo`.`users`  ;

CREATE TABLE users (
  id VARCHAR(40) PRIMARY KEY NOT NULL DEFAULT (UUID()),
  first_name VARCHAR(55) NOT NULL,
  last_name VARCHAR(55) NOT NULL,
  email VARCHAR(100) NOT NULL,
  phone VARCHAR(45) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  updated_at DATETIME on UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  UNIQUE INDEX email_UNIQUE (email ASC) VISIBLE
);
